### ISSUE TITLE
mkv support

### ISSUE THREAD

**Issue by JoatWiPete** [thekirankumar/youtube-android-auto#18]
Any way to add support for mkv files or subtitles when playing from local offline offline storage? 
Thanks for the work you put in on this project.

**Comment by thekirankumar** [comment]
Currently can be done through Plex. Just install plex media server along with plex app on your phone, set it up and then visit http://app.plex.tv on CarStream or just click the plex.tv bookmark.
Then you can see all the local movies, music, playlists etc via plex UI.

**Comment by thekirankumar** [comment]
Giving native MKV support is a hard problem and I can never achieve Plex like perfection, hence not taking this up now.

**Comment by thekirankumar** [comment]
Please reopen the issue if you are still facing problems

**Comment by FameT** [comment]
Kiran, I was not able to understand how to play local mkv's using plex. Could you please tell a bit more? I've installed plex on my phone, but I haven't found server app for phone. As I can understand, my phone should be server that sends videostream to webview inside CarStream. Another question: does all the traffic make a loop via internet in this case. Or plex is clever enough to use local server without internet usage. Does this work without any internet connection?
