### ISSUE TITLE
Video feeds freezing after playing a while (except Youtube)

### ISSUE THREAD

**Issue by kaisertgc** [thekirankumar/youtube-android-auto#2]
Hi,
I tried many websites. Usually it is freezing after some time. Just Yoitube videos plays fine. Thanks.

**Comment by thekirankumar** [comment]
Is it working in new version ? Someone mentioned that it got fixes

**Comment by kaisertgc** [comment]
Yes yes it is fixed. Thanks. Just it would be nice to have Favorites section. We can set our favorite tv's url adresses on phone then quickly select from car.

**Comment by thekirankumar** [comment]
Yes, will be adding this next over the weekend
