### ISSUE TITLE
Is it really dead ? (MIB2 ToolBox - Allow custom app...)

### ISSUE THREAD

**Issue by shaarkys** [thekirankumar/youtube-android-auto#257]
https://github.com/jilleb/mib2-toolbox does support Android Auto Custom apps - https://github.com/jilleb/mib2-toolbox/blob/master/Toolbox/scripts/patch_gal.sh - isn't that solution as well ? Actually I can launch CarStream but I get loading "for ever", like already described here - https://github.com/thekirankumar/carstream-android-auto/issues/242

@thekirankumar Any thoughts please ?

**Comment by croccio** [comment]
here u are https://github.com/croccio/CarTube/releases
