### ISSUE TITLE
APP CRASH ERROR

### ISSUE THREAD

**Issue by Maxdashsu** [thekirankumar/youtube-android-auto#32]
Hi Kiran,

me and some other people are getting the app crashed when open it on AA (black display), getting an error message like the one reported below.  I’m using the phone Honor 9.  Can you help to solve this problem? Why is it crashing? What I have noted is that unistalling and installing again AA from the Play Store the app comes back to work normally, but only for once, at the second connection still have the same error and crash.  Thanks in advance for your support in solving this issue. 
**"Maxcar crashed
java.lang.RuntimeException: Unable to create serrvice com.thekirankumar.youtubeauto.service.CarService: java.lang.RuntimeException:com.google.android.gms.car.b:java.lang.reflect.InvocationTargetException at andorid.app.ActivityThread.handleCreateService(ActivityThread.java:3362) at andoidapp.ActivityThread.-wrap5(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1662)"**

**Comment by thekirankumar** [comment]
Which phone and which version of android ?

**Comment by Maxdashsu** [comment]
Hi, the phone is Honor 9 (huawei) with Android 7.0 EMUI 5.1

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by thekirankumar** [comment]
Huawei phones dont work well with Android auto. Im guessing even Waze app on auto doesnt work well for you right ?
Many have reported here https://forum.xda-developers.com/android-auto/android-auto-general/android-auto-compatible-huawei-phones-t3744725/page2
