### ISSUE TITLE
Support for Non-Touchscreen in Bookmarks

### ISSUE THREAD

**Issue by sflyfoxx** [thekirankumar/youtube-android-auto#35]
Request to add support for non-touchscreen navigation within Bookmarks page.  Currently, the cursor/ selector does not enter the bookmark area.  It jumps from the top bar to the AA bottom bar, skipping the bookmark area when the car button/ joystick is click.  Thanks.

**Comment by thekirankumar** [comment]
This is fixed in latest version 1.8.2. Reopen this issue if it hasnt.
