### ISSUE TITLE
Doesn't open up properly 

### ISSUE THREAD

**Issue by tomasz0000** [thekirankumar/youtube-android-auto#37]
Hi, I have a problem. I did everything what was in instalation and unblocking video. Android auto sees the car stream app but when I enter it looks like a normal player app and in the openable bar on the left there are no elements. What else I can do to make it work. (phone galaxy s8 car seat leon 2017)

**Comment by thekirankumar** [comment]
You need to click on the last icon. The one to the right of the headphone icon. It looks like a speedometer. If single click doesnt work, doube click.
