### ISSUE TITLE
Disable pause when switching activity

### ISSUE THREAD

**Issue by cmeka** [thekirankumar/youtube-android-auto#41]
Firstly, thank you for the amazing app and continued development!

This isn't really an issue, I'm just wondering if there's a way to have the app not pause a playing stream when switching away from your app, eg. to continue playing in background when opening up maps on the bottom nav bar. This could be an optional feature if it were implemented.
If you don't think it's needed may you please point me where in the code to implement it so I could attempt it?
Do you know which function gets called when switching away from the app?
I've been experimenting with [onPause](https://github.com/thekirankumar/youtube-android-auto/blob/7cbcc829d807137f4c0eebd53b23f37a66cdb6e9/app/src/main/java/com/thekirankumar/youtubeauto/fragments/WebViewCarFragment.java#L890) commenting out pauseVideoAndSetFlag or changing it to playVideoIfPausedFlag with no success.

**Comment by thekirankumar** [comment]
Haha, glad to see a fellow developer here.
Its not related to onPause. Its the problem with losing audio focus. I've not implemented the audio focus gain properly, refer this :
https://developer.android.com/guide/topics/media-apps/audio-focus.html 
Maybe holding onto the audio focus when playing and losing it when playback is stopped will work.
Thanks for helping and do raise a PR.

**Comment by cmeka** [comment]
Ah thank you, I'm more a web developer and just a beginner in android development but your app piqued my interest.
If I understand correctly, if we were to regain audio focus when lost every time if something's playing, that would override other music apps from playing until the stream in this app is paused manually.

After looking at the android activity lifecycle, I think a possible solution would be to add the onStop function in MainCarActivity which should fire when switching apps, then regain focus and continue playback. I'll experiment with this soon.

**Comment by thekirankumar** [comment]
Well its more complicated than that, I have fixed the issue in v1.8.3
Please check and let me know. You can look at the recent commits to know how.
