### ISSUE TITLE
Build: strings to be matched

### ISSUE THREAD

**Issue by pdario** [thekirankumar/youtube-android-auto#44]
I cloned master and built the APK: there are some strings to be matched.

    <string name="send_to_car">
    <string name="receive_from_phone">

Do not match between generic language and BT, ES, IT and TH.

BTW: isn't there any tag for released version??

**Comment by thekirankumar** [comment]
I think the last set of PRs should have fixed this.
https://github.com/thekirankumar/youtube-android-auto/pulls?q=is%3Apr+author%3Ashmykelsa

**Comment by thekirankumar** [comment]
I've been putting a separate commit for each release. Have started using tags since last release.

**Comment by pdario** [comment]
Hello, I just reset to origin but I still get build errors on strings:

[.......]\app\src\main\res\values-ro\strings.xml
Error:(14) Error: "send_to_car" is translated here but not found in default locale [ExtraTranslation]
Error:(20) Error: "receive_from_phone" is translated here but not found in default locale [ExtraTranslation]
