### ISSUE TITLE
Help Translate to Dutch

### ISSUE THREAD

**Issue by JSibelo** [thekirankumar/youtube-android-auto#56]
I Am offering to translate the app to the Dutch, how do I do this?

**Comment by thekirankumar** [comment]
This is the strings file https://github.com/thekirankumar/youtube-android-auto/blob/master/app/src/main/res/values/strings.xml
Fork this repo, [create new strings.xml for dutch](https://stackoverflow.com/questions/44477221/easiest-way-to-translate-android-strings-xml-file), commit it back to the repo and create a PR
