### ISSUE TITLE
Sometime app stop to works

### ISSUE THREAD

**Issue by ellenamatteo** [thekirankumar/youtube-android-auto#59]
Sometime app stop to works (during playing video) ,
then when i try to restart app screen still black.
To restore app i need to reinstall AA and CarStream

**Comment by thekirankumar** [comment]
Which phone and android OS version ?

**Comment by ellenamatteo** [comment]
Huawei P10 Lite.....

**Comment by thekirankumar** [comment]
Huawei phones have problems related to Android auto, it's also mentioned in xda. Does Waze app also have this problem, can you please check.

**Comment by ellenamatteo** [comment]
Hi,
i have tested app.....
When CarStream crash Android Auto stop to work and my "Car Radio" return to the home screen....
Relaunching AA all seem work well but when select CarStream again screen still "black".
This evening i tried to clear only CarStream cache and app return to work correctly.
With 1.7 Version "clean cache" method did not work (and i need to reinstall all).
I suppose that issue is about caching of the new local video player, 
Can be a good idea if when CarStream detect an error in local cache "auto reset" this or ignore error (like as "resume next").
What do you think about ?
Bye

**Comment by ellenamatteo** [comment]
Hi again,
i discovered that AA issue ("Car Radio" return to the home screen) was caused by an usb hub i use to connect phone + an usb key ....
Removing hub AA work well and mi "Car Radio" don't return to the come screen......
CarStream sometimes continue to crash and "restart" but for the moment i don't need to reinstall all again.

Thanks

**Comment by ahhl** [comment]
@thekirankumar
i am on mate 7. no issue with waze or sportify

**Comment by thekirankumar** [comment]
Yes, carstream crashes once a day. But not a major problem since it resumes from where it left off. Closing for now. 
@ahhl many of the huawei devices have black screen, dont know why.
