### ISSUE TITLE
Suggestion - App naming - Avoid any legal conflict or 'war' with Google

### ISSUE THREAD

**Issue by nerone-github** [thekirankumar/youtube-android-auto#6]
Hi, i think you should consider to rename your application to comply with the guidelines for Android app naming. I know that the app is not in the PlayStore - Still you should consider to change it, because it could trigger a conflict with google resulting in a possible block of all third-party AA apps. 

Since you said yourself on your blog that google might have blocked your previous apk this could be a reason..

https://play.google.com/about/developer-content-policy-print/
https://stackoverflow.com/questions/28755825/android-app-naming-guidelines-first-word-as-company

Youtube Auto especially with that logo is probably an impersonation.

For example you could name rename it:

- CarPlayer for YouTube
- *whatever* for YouTube

**Comment by Hertizch** [comment]
It is basically a web browser, so it should not be called youtube at all! That's just my opinion...

**Comment by thekirankumar** [comment]
Thank you @nerone-github  Yes, I'm still figuring out a good name.

**Comment by thekirankumar** [comment]
How about CarDashian since it runs on your dashboard.

**Comment by thekirankumar** [comment]
Or Tomauto

**Comment by thekirankumar** [comment]
Or something generic like Ultimate media browser or something liek that ?

**Comment by nerone-github** [comment]
I would go with a name which already gives a hint about what the program does, so i am not a fan of tomauto ir cardashian.  

Maybe just wait for a more creative name but if i were you i would at least change the logo and the YouTube naming asap before Google will take steps. Names like XYZ "for YouTube" are less against copyright

 Remember that they killed the YouTube app by MS on the windows phone ;)

**Comment by thekirankumar** [comment]
Agreed, will release an update soon

**Comment by thekirankumar** [comment]
I founded CarDashian funny though :D

**Comment by thekirankumar** [comment]
What do you think of "YouStream"

**Comment by nerone-github** [comment]
I Don't know, i feel like the connection to cars is missing, but you choose :) 

Maybe some other random ideas: HeadYounit HeadunitMedia HeadunitPlayer StreamToCar CarMedia AutoPlayer AutoStream etc. Of course make a quick Google search to see if other have already similar products. 

Maybe if you can't choose you can pick some ideas you like best and then create a poll/vote .

BTW - Did you find out the reason why the app did not work? I'd really like to know if google actually can block AA apks even if unknown sources is active. Maybe they have some sort of hashcode blacklist? and each package is validated against some server..?

**Comment by thekirankumar** [comment]
Ok, CarStream sounds good for now. Ran a poll and the user believe the same.
Google did send me a mail yesterday 

01/16/2018

VIA EMAIL (gmail@thekirankumar.com) 

To Whom It May Concern:

We recently became aware of your service, YoutubeAuto, which is being offered at http://www.thekirankumar.com/blog/2017/12/29/play-youtube-video-android-auto-app/. It appears from your website and other marketing materials that YoutubeAuto plays YouTube content in the background, meaning the audio and visual content is not displayed in the page, tab, or screen that the user is viewing, and plays YouTube content using technology other than the Embedded Player. We need to ask you to stop offering that functionality.

You may be aware that the YouTube Terms of Service, which are posted at http://www.youtube.com/t/terms, state "you agree not to alter or modify any part of the Service" [Section 4B] and "you may not modify, build upon, or block any portion or functionality of the Embeddable Player" [Section 4F].“you agree not to access Content through any technology or means other than the video playback pages of the Service itself, the Embeddable Player, or other explicitly authorized means YouTube may designate” [Section 4C]. In addition, the YouTube API Terms of Service, which are available at https://developers.google.com/youtube/terms state you and your API Clients must not, and must not encourage, enable, or require others to: (i) "create, include, or promote features that play content, including audio or video components, from a background player, meaning a player that is not displayed in the page, tab, or screen that the user is viewing" (ii) "separate, isolate or modify the audio or video components of any YouTube audiovisual content" or (iii) "promote separately the audio or video components of any YouTube audiovisual content" [Developer Policies Section I.7-9]."use any technology other than YouTube API Services to access or retrieve API Data, including to access any portion of any YouTube audiovisual content" [Developer Policies Section I.14]. Continuing to violate these restrictions may result in legal consequences for you and/or your company.

In addition, your product uses YouTube’s protected trademarks, such as our name and our icon. This likely confuses consumers as to the source of YoutubeAuto and whether YoutubeAuto is affiliated with or approved by YouTube. This is also a legal problem.

We strive to keep YouTube a safe, responsible community, and to encourage respect for the rights of millions of YouTube creators. This requires compliance with the Terms of Service and API Terms of Service, as well as respect for YouTube’s registered trademarks. We hope that you will cooperate with us by ceasing to offer YoutubeAuto with functionality that plays YouTube content in the background, meaning the audio and visual content is not displayed in the page, tab, or screen that the user is viewing, plays YouTube content using technology other than the Embedded Player within seven days from the date of this letter, and by complying with the YouTube Branding Guidelines available at https://developers.google.com/youtube/branding. Thank you in advance.



Sincerely,

The YouTube Legal Team

**Comment by thekirankumar** [comment]
Regarding the blocking of the app, google did block youtubeauto's original package name. It looks like a simple package name check when they did so. Changing my package name fixed it. Atleast once I change the name and remove background playback, they should be happy.

**Comment by nerone-github** [comment]
and the logo / icon ;) maybe you can also use a poll or contest for the logo. To create a simple / neutral logo you can use the asset creator in AS.

**Comment by ahhl** [comment]
saw someone mentioned cartube, or youcar 😗

**Comment by b0riska** [comment]
Would you consider more options, e.g. TubeAuto, YouPlay, NuTube?

**Comment by b0riska** [comment]
Yo! Tube :)

**Comment by nerone-github** [comment]
I would keep out the You  and Tube from the name else the next email from Google will follow soon i guess ;)

**Comment by b0riska** [comment]
It's a pity. I see many apps in Google Play with the names containing all those You and Tube in different combinations.

**Comment by nerone-github** [comment]
It depends for what it is. Calling a camera YouCam is ok, but for an app that plays YouTube its not.
Also sooner or later those apps will get a cease and desist letter too

**Comment by nerone-github** [comment]
Hi, i think you should remove also the previous *.apk downloads named youtubeauto and basically remove that name from everything on your blog, package name etc. else you won't make google happy if users can still download a product which violates their TOS ;)

**Comment by nerone-github** [comment]
Also don't use com.google package name. That's a big NO. Please try to solve this legal stuff quickly. The last we want is that Google is so pissed about this that they are going to allow only signed apks for AA. That would KILL the whole custom SDK stuff for good.

**Comment by thekirankumar** [comment]
That Package name was a desperate attempt to unblock the app, but I guess google got bored of this now. So we are good.
