### ISSUE TITLE
Add a little clock as Overlay on videos

### ISSUE THREAD

**Issue by ellenamatteo** [thekirankumar/youtube-android-auto#60]
It's great if you can add a little clock as overlay on videos. Now thre is only a clock in "command bar" but i need tu push video to show it.

**Comment by thekirankumar** [comment]
Won't this be irritating to have it always there ? I guess have it as a setting disabled by default will help

**Comment by ellenamatteo** [comment]
I think that if clock is little in the upper right is not a problem (Playing local videos)....

**Comment by thekirankumar** [comment]
Keeping this. Will do in future, since it requires a little more thought and not many users are requesting this feature.
