### ISSUE TITLE
Auto Brightness 

### ISSUE THREAD

**Issue by JustinSelvakumar** [thekirankumar/youtube-android-auto#62]
Hi Kiran,

is there any possibility to set Auto brightness in your application instead changing the brightness in system.
this would help while night drive to have low brightness in watching videos.

Btw, the app is awesome - 5star... :-)

**Comment by thekirankumar** [comment]
Doesn't your car already lower brightness when headlights are switched on.

**Comment by JustinSelvakumar** [comment]
Yes. those things are working and not for video with high brightness.
Try with this - https://www.youtube.com/watch?v=6v2L2UGZJAM
felt like flash on my face.
is it possible to bring something similar like how MXplayer does it.
even it will help in increasing more brightness in day/night based on the need. :-)

people would love it.

**Comment by shmykelsa** [comment]
The brightness of the car's screen is adjusted by the car itself, so the app can do nothing about it

**Comment by JustinSelvakumar** [comment]
the brightness is auto adjusted in AA for all features in my Smart Infotainment system. except for car stream.
hope you guys can simulate it and check if required.

**Comment by thekirankumar** [comment]
Brightness is controlled by android auto globally and not specific to any app.
It should work for carstream too. The only way to workaround is to dim the video view's opacity itself which is hacky. Not doing this for now.

**Comment by JustinSelvakumar** [comment]
thanks kiran. appreciated.
we are looking for new features. all the best.
