### ISSUE TITLE
car stream reader does not work

### ISSUE THREAD

**Issue by tig2017** [thekirankumar/youtube-android-auto#64]
good afternoon, I am owner of a smartphone lg g4 with android 6.0
I installed version 1.8.3 of the app, but when I start the car stream and I want to switch to the car stream reader it does not work and it does not make the youtube music I have previously chosen. At the same time it does not allow me to use spotify, which is no longer in the android auto app.  Can you do something to fix this bug? thank you

**Comment by thekirankumar** [comment]
I am not able to understand the issue? How about explain using a video ?
