### ISSUE TITLE
Full screen Video with auto hide android auto icons

### ISSUE THREAD

**Issue by raja118** [thekirankumar/youtube-android-auto#66]
Full screen Video with auto hide android auto icons

**Comment by Sirek4s** [comment]
But can i disable popup bar above, when the new track begins on youtube or i visit a new webpage?

**Comment by shmykelsa** [comment]
These are the notifications from the player. The player is there so you can listen to videos in background and you can use the scrollwheel on the steering wheel. So I don't think it's possible

**Comment by thekirankumar** [comment]
Do you mean the popup which appears for few seconds and disappears ? Or the black bar on top which has all the control buttons ?
Bottom bar hiding is not possible. Top bar hiding happens in full screen mode.

**Comment by Sirek4s** [comment]
Yes, i mean the popup which appears for few seconds and u can close it from X also. For me personally a bit annoying and unnecessary. But overall great app. One of the best apps in my phone.

**Comment by ilikenwf** [comment]
Could a modified version of the android auto app work? If a rom is patched to support signature spoofing, or has xposed, we could probably disable it if it is a function of the phone and not the head unit.

There's also a reversed server for auto, I wonder if we couldn't just replicate the portal as an app and not require all of google's garbage?
https://github.com/f1xpl/openauto
