### ISSUE TITLE
Review dependencies e.g. Firebase should not be needed

### ISSUE THREAD

**Issue by nerone-github** [thekirankumar/youtube-android-auto#7]
Probably those can be safely removed since firebased isn't use in the code. 

implementation 'com.google.firebase:firebase-core:11.0.4'
implementation 'com.google.firebase:firebase-messaging:11.0.4'
implementation 'com.google.firebase:firebase-crash:11.0.4'

**Comment by thekirankumar** [comment]
I use it, for tracking and crash reporting. There is no code written, but its automatically sending data just because I included it.

**Comment by Ysandeep7970** [comment]
I'm having the same issue recently on pixel 7 non r
