### ISSUE TITLE
Steering Wheels command cause Crash

### ISSUE THREAD

**Issue by ellenamatteo** [thekirankumar/youtube-android-auto#77]
Hi,

sometime using Steering Wheels command app crash....

Always , when carstream play local file and the file played is the last, if i select "next" app crash.

you can find a video explaining issue at this link .

https://drive.google.com/file/d/1p9Whr3G1B6Ov4JDelwEtkZUPUSMiXdzl/view?usp=sharing

Thank you

**Comment by thekirankumar** [comment]
Thanks for the awesome video explaining the crash. Fix will be in next update

**Comment by ellenamatteo** [comment]
Thanks !!!
