### ISSUE TITLE
App disappeared from OEM screen after reboot

### ISSUE THREAD

**Issue by pinballnewf** [thekirankumar/youtube-android-auto#8]
Was working fine, until device reboot - [Pixel].  Now missing from android auto app selector screen.
Other unofficial app I have installed still listed and works.  Tried uninstalling, reinstalling, tried previous version from 2 days ago.  Tried disabling & re-enabling developer mode [and unofficial sources]. Tried erasing android auto pairing from headunit [Sync 3]
Another phone with youtube-android-auto [S8] currently still shows the app in selector screen.

**Comment by pinballnewf** [comment]
Ah, I see you sent a push notification about google blocking again.  Will try the updated version and see if that works and if so will close issue

**Comment by thekirankumar** [comment]
Yes. 1.6 version should again unblock it.
