### ISSUE TITLE
@ not possible intro from keyboard 

### ISSUE THREAD

**Issue by flyingsinver** [thekirankumar/youtube-android-auto#81]
Hello 

I can't intro @ from keyboard in web search CarStream app.

Please, can you implement it ?

From Spain,
Thank you very much 
Very good job !!!

Best regards,
Chema

**Comment by thekirankumar** [comment]
Duplicate of #22 
Will be added but requires a lot of work. Taking up next after bookmark settings
In the meantime, use the phone carstream app to login once.
