### ISSUE TITLE
Finnish Yle Areena suggest Areena app for non live videos

### ISSUE THREAD

**Issue by McPaHa** [thekirankumar/youtube-android-auto#82]
Hi!

It seems that newest version 1.8.3 is seeing as a mobile browser? because Yle Areena (areena.yle.fi) suggests areena app for stored videos. Live channels are working just fine. Some (maybe all) videos are geo blocked so if you want to test itself you need vpn for Finland. Version 1.7.3 works just fine...

**Comment by thekirankumar** [comment]
There is no change in 1.8.3 which should trigger this.

**Comment by thekirankumar** [comment]
Also the next update will allow you to have desktop mode

**Comment by thekirankumar** [comment]
Trackable via #24
