### ISSUE TITLE
Pop-up for next songs in header is annoying

### ISSUE THREAD

**Issue by JustinSelvakumar** [thekirankumar/youtube-android-auto#83]
Could we do something about displaying the nextsong details/youtube in system header.

it is actually annoying.

**Comment by JustinSelvakumar** [comment]
also sometimes, the header icons are still present in full screen mode. only after touching the screen it disappears.
or i need to touch the full screen mode 2 times.

**Comment by thekirankumar** [comment]
There is a setting to disable this popup in next version

**Comment by JustinSelvakumar** [comment]
awesome. great.
